export const FETCH_STOCK_REQUEST = "FETCH_STOCK_REQUEST";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAILURE = "FETCH_STOCK_FAILURE";
export const FILTER_STOCK_DATA = "FILTER_STOCK_DATA";

